// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBheZ3srWRowp0ZqEXBpUBBfR9x0SJVEgk',
    appId: '1:1023373959658:android:18f56415bf83a458d25293',
    messagingSenderId: '1023373959658',
    projectId: 'travel-f87f8',
    databaseURL: 'https://travel-f87f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-f87f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbz-QhfBKgm--UaiGU_vctdMsDsVA-Xi4',
    appId: '1:1023373959658:ios:eceed0e87a2cad4ad25293',
    messagingSenderId: '1023373959658',
    projectId: 'travel-f87f8',
    databaseURL: 'https://travel-f87f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-f87f8.appspot.com',
    iosClientId: '1023373959658-abmhj9gol6ruo0mvarbhrpckkj79kngp.apps.googleusercontent.com',
    iosBundleId: 'com.kupstuido.travelidge',
  );
}
